[env]
DEFMT_LOG="debug"

[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]

# Syntax is: probe-rs test <flash settings> -- <elf> <libtest args>
runner = "probe-rs test --chip STM32F411CEUx -- "

rustflags = [
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",

    # "-C", "link-arg=-Tstlog.x",

    # if you run into problems with LLD switch to the GNU linker by commenting out
    # this line
    # "-C", "linker=arm-none-eabi-ld",

    # if you need to link to pre-compiled C libraries provided by a C toolchain
    # use GCC as the linker by commenting out both lines above and then
    # uncommenting the three lines below
    # "-C", "linker=arm-none-eabi-gcc",
    # "-C", "link-arg=-Wl,-Tlink.x",
    # "-C", "link-arg=-nostartfiles",
]